name: Build Plugin

on: workflow_dispatch

jobs:
  windows:
    name: windows build
    runs-on: windows-latest
    env:
      HL2SDKCS2: ${{ github.workspace }}/cs2fixes/sdk

    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/alliedmodders/ambuild

      - name: Checking out MM:Source
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: mmsource-2.0
          submodules: recursive

      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          path: cs2fixes
          submodules: recursive

      - name: Install Clang 16
        if: matrix.os == 'ubuntu-latest'
        run: |
          apt update && apt install -y clang-16
          ln -sf /usr/bin/clang-16 /usr/bin/clang && ln -sf /usr/bin/clang++-16 /usr/bin/clang++

      - name: Compiling files
        working-directory: cs2fixes
        shell: cmd
        run: |
          mkdir build && cd build
          python3 ..\configure.py --enable-optimize --symbol-files --sdks cs2
          ambuild
          
      - name: Uploading package
        uses: actions/upload-artifact@v3
        with:
          name: cs2fixes-windows-${{ env.GITHUB_SHA_SHORT }}
          path: cs2fixes/build/package
